[package]
name = "lantern"
version = "0.1.0"
authors = ["Sahil Iyer <iyersahil12@gmail.com>"]
edition = "2018"

[dependencies]
log = { path = "../log" }
gl = "0.11.0"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"
default_features = false
